# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = Frontend-RSA
DESTDIR = ./x64/Debug
CONFIG += debug
LIBS += -L"C:/Boost/boost_1_77_0/stage/lib"
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += debug
UI_DIR += .
RCC_DIR += .
include(Frontend-RSA.pri)
